# Generated automatically from Makefile.in by configure.
SHELL = /bin/sh

FC = gfortran
FFLAGS= -ffree-form

MAIN_LIB_PATH="/Users/mathieumoog/Softwares/LibAtomicSim/Fortran/"


test:
	-$(FC) -c $(MAIN_LIB_PATH)utils.o -o test.x


clean:
	@rm *.mod *.o *~
