# Generated automatically from Makefile.in by configure.
SHELL = /bin/sh

FC = gfortran
FFLAGS= -ffree-form

ALL = utils conversion xyz

$(ALL):
	-$(FC) -c $@.f90

all: $(ALL) 

clean:
	@rm *.mod *.o
